USE []
GO

CREATE TABLE [Currencies]
(
	[ID] TINYINT IDENTITY(1,1) CONSTRAINT [PK_Currencies_ID] PRIMARY KEY,
	[Type] VARCHAR(30) NOT NULL,
	[Short] VARCHAR(3) NOT NULL CONSTRAINT [UN_Currencies_Short] UNIQUE CONSTRAINT [CK_Currencies_Short] CHECK ([Short] LIKE '[A-Z][A-Z][A-Z]')
)
GO


CREATE TABLE [CurrencyRates]
(
	[ID] INTEGER IDENTITY(1,1) CONSTRAINT [PK_CurrencyRates_ID] PRIMARY KEY,
	[CurrencyID] TINYINT NOT NULL CONSTRAINT [FK_CurrencyRates_CurrencyID] FOREIGN KEY REFERENCES [Currencies]([ID]) ON UPDATE CASCADE ON DELETE CASCADE,
	[Rate] NUMERIC(10,2) NOT NULL CONSTRAINT [CK_CurrencyRates_Rate] CHECK ([Rate] >= 0),
	[DateOfRate] DATE NOT NULL CONSTRAINT [DEF_CurrencyRates_DateOfRate] DEFAULT TRY_CONVERT(DATE, CURRENT_TIMESTAMP)
)
GO


CREATE TABLE [BusinessUnitTypes]
(
	[ID] TINYINT IDENTITY(1,1) CONSTRAINT [PK_BusinessUnitTypes_ID] PRIMARY KEY,
	[BusinessUnitType] VARCHAR(10) NOT NULL CONSTRAINT [UN_BusinessUnitTypes_BUT] UNIQUE
)
GO


CREATE TABLE [BusinessUnits]
(
	[ID] SMALLINT IDENTITY(1,1) CONSTRAINT [PK_BusinessUnits_ID] PRIMARY KEY,
	[BusinessUnitTypeID] TINYINT NOT NULL CONSTRAINT [FK_BusinessUnits_BusinessUnitTypeID] FOREIGN KEY REFERENCES  [BusinessUnitTypes]([ID])  ON UPDATE CASCADE ON DELETE NO ACTION,
	[OpeningDate] DATE NOT NULL,
	[Name] VARCHAR(20) NOT NULL,
	[Country] VARCHAR(30) NOT NULL,
	[State] VARCHAR(30) NOT NULL,
	[City] VARCHAR(30) NOT NULL,
	[PostalCode] CHAR(5) NOT NULL CONSTRAINT [CK_BusinessUnits_PostalCode] CHECK ([PostalCode] LIKE '[0-9][0-9][0-9][0-9][0-9]'),
	[Address] VARCHAR(50) NOT NULL,
	[Phone]	VARCHAR(15) NOT NULL,
	[IsActive] BIT NOT NULL
)
GO


CREATE TABLE [Discounts]
(
	[ID] TINYINT IDENTITY(1,1) CONSTRAINT [PK_Discounts_ID] PRIMARY KEY,
	[Percent] TINYINT NOT NULL CONSTRAINT [CK_Discounts_Percent] CHECK ([Percent] BETWEEN 0 AND 100),
	[MinSum] NUMERIC(10,2) NOT NULL CONSTRAINT [CK_Discounts_MinSum] CHECK ([MinSum] >=0),
	[Description] VARCHAR(50) NULL
)
GO


CREATE TABLE [Customers]
(
	[ID] INT IDENTITY(1,1) CONSTRAINT [PK_Customers_ID] PRIMARY KEY,
	[FirstName] VARCHAR(30) NOT NULL,
	[LastName] VARCHAR(30) NOT NULL,
	[Gender] CHAR(1) NOT NULL CONSTRAINT [CK_Customers_Gender] CHECK ([Gender] LIKE '[-MFmf?]'),
	[DiscountID] TINYINT NOT NULL CONSTRAINT [DEF_Customers_DiscountID] DEFAULT (3) CONSTRAINT [FK_Customers_DiscountID] FOREIGN KEY REFERENCES [Discounts]([ID]) ON UPDATE CASCADE ON DELETE SET DEFAULT,
	[RegistrationDate] DATE NOT NULL CONSTRAINT [DEF_Customers_RegistrationDate] DEFAULT TRY_CONVERT(DATE, CURRENT_TIMESTAMP),
	[TotalSum] NUMERIC(10, 2) NOT NULL CONSTRAINT [CK_Customers_TotalSum] CHECK ([TotalSum] >=0) CONSTRAINT [DEF_Customers_TotalSum] DEFAULT (0),
	[Phone] VARCHAR(15) NOT NULL,
	[Email] VARCHAR(40) NOT NULL,
	[BirthDate] DATE NULL,
	[Country] VARCHAR(30) NOT NULL,
	[State] VARCHAR(30) NOT NULL,
	[City] VARCHAR(30) NOT NULL,
	[PostalCode] CHAR(5) NOT NULL CONSTRAINT [CK_Customers_PostalCode] CHECK ([PostalCode] LIKE '[0-9][0-9][0-9][0-9][0-9]'),
	[Address] VARCHAR(30) NULL
)
GO


CREATE TABLE [Roles]
(
	[ID] SMALLINT IDENTITY(1,1) CONSTRAINT [PK_Roles_ID] PRIMARY KEY,
	[Name] VARCHAR(30) NOT NULL CONSTRAINT [UN_Roles_Name] UNIQUE,
	[Salary] NUMERIC(10, 2) NOT NULL CONSTRAINT [CK_Roles_Salary] CHECK ([Salary] >= 0)
)
GO


CREATE TABLE [Employees]
(
	[ID] INT IDENTITY(1,1) CONSTRAINT [PK_Employees_ID] PRIMARY KEY,
	[FirstName] VARCHAR(30) NOT NULL,
	[LastName] VARCHAR(30) NOT NULL,
	[Gender] CHAR(1) NOT NULL CONSTRAINT [CK_Employees_Gender] CHECK ([Gender] LIKE '[MFmf]'),
	[BirthDate] DATE NOT NULL,
	[Phone] VARCHAR(15) NOT NULL,
	[Email] VARCHAR(40) NOT NULL CONSTRAINT [UN_Employees_Email] UNIQUE,
	[Country] VARCHAR(30) NOT NULL,
	[State] VARCHAR(30) NOT NULL,
	[City] VARCHAR(30) NOT NULL,
	[PostalCode] CHAR(5) NOT NULL CONSTRAINT [CK_Employees_PostalCode] CHECK ([PostalCode] LIKE '[0-9][0-9][0-9][0-9][0-9]'),
	[Address] VARCHAR(30) NOT NULL
)
GO


CREATE TABLE [EmployeeRoles]
(
	[ID] INT IDENTITY(1,1) CONSTRAINT [PK_EmployeeRoles_ID] PRIMARY KEY,
	[EmployeeID] INT NOT NULL CONSTRAINT [FK_EmployeeRoles_EmployeeID] FOREIGN KEY REFERENCES [Employees]([ID]) ON UPDATE CASCADE ON DELETE CASCADE,
	[RoleID] SMALLINT NOT NULL CONSTRAINT [FK_EmployeeRoles_RoleID] FOREIGN KEY REFERENCES [Roles]([ID]) ON UPDATE CASCADE ON DELETE NO ACTION,
	[BusinessUnitID] SMALLINT NOT NULL CONSTRAINT [FK_EmployeeRoles_BusinessUnitID] FOREIGN KEY REFERENCES [BusinessUnits]([ID]) ON UPDATE CASCADE ON DELETE NO ACTION,
	[StartDate] DATE NOT NULL,
	[EndDate] DATE NULL,
	[Description] VARCHAR(255) NULL 
)
GO


CREATE TABLE [Categories] 
(
	[ID] SMALLINT IDENTITY(1,1) CONSTRAINT [PK_Categories_ID] PRIMARY KEY, 
	[Name] VARCHAR(50) NOT NULL CONSTRAINT [UN_Categories_Name] UNIQUE,
	[Description] VARCHAR(255) NULL
)
GO


CREATE TABLE [Subcategories] 
(
	[ID] SMALLINT IDENTITY(1,1) CONSTRAINT [PK_Subcategories_ID] PRIMARY KEY,
	[CategoryID] SMALLINT NOT NULL CONSTRAINT [FK_Subcategories_CategoryID] FOREIGN KEY REFERENCES [Categories]([ID]) ON UPDATE CASCADE ON DELETE NO ACTION,
	[Name] VARCHAR(50) NOT NULL,
	[Description] VARCHAR(255) NULL,
	[IsAviable] BIT NOT NULL CONSTRAINT [DEF_Subcategories_IsAviable] DEFAULT (1),
)
GO


CREATE TABLE [Guaranties] 
(
	[ID] TINYINT IDENTITY(1,1) CONSTRAINT [PK_Guaranties_ID] PRIMARY KEY,
	[Duration] TINYINT NOT NULL,
	[Description] VARCHAR(30) NULL
)
GO


CREATE TABLE [Vendors] 
(
	[ID] SMALLINT IDENTITY(1,1) CONSTRAINT [PK_Vendors_ID] PRIMARY KEY,
	[Name] VARCHAR(40) NOT NULL CONSTRAINT [UN_Vendors_Name] UNIQUE,
	[Country] VARCHAR(40) NOT NULL,
	[City] VARCHAR(30) NOT NULL,
	[Phone] VARCHAR(15) NOT NULL,
	[Email] VARCHAR(40) NOT NULL CONSTRAINT [UN_Vendors_Email] UNIQUE,
	[IsActive] BIT NOT NULL CONSTRAINT [DEF_Vendors_IsActive] DEFAULT (1),
	[CurrencyID] TINYINT NOT NULL CONSTRAINT [DEF_Vendors_CurrencyID] DEFAULT(1) CONSTRAINT [FK_Vendors_CurrencyID] FOREIGN KEY REFERENCES [Currencies]([ID])
)
GO


CREATE TABLE [Products] 
(
	[ID] INT IDENTITY(1, 1) CONSTRAINT [PK_Products_ID] PRIMARY KEY,
	[VendorID] SMALLINT NOT NULL CONSTRAINT [FK_Products_VendorID] FOREIGN KEY REFERENCES [Vendors]([ID]) ON UPDATE CASCADE ON DELETE NO ACTION,
	[SubcategoryID] SMALLINT NOT NULL CONSTRAINT [FK_Products_SubcategoryID] FOREIGN KEY REFERENCES [Subcategories]([ID]) ON UPDATE CASCADE ON DELETE NO ACTION,
	[Model] VARCHAR(100) NOT NULL CONSTRAINT [UN_Products_Model] UNIQUE,
	[Color] VARCHAR(20) NULL,
	[Description] VARCHAR(30) NULL,
	[GuarantyID] TINYINT NOT NULL CONSTRAINT [FK_Products_GuarantyID] FOREIGN KEY REFERENCES [Guaranties]([ID]) ON UPDATE CASCADE ON DELETE NO ACTION,
	[RetailPrice] NUMERIC(10, 2) NOT NULL CONSTRAINT [CK_Products_RetailPrice] CHECK ([RetailPrice] > 0)
)
GO


CREATE TABLE [Stocks]
(
	[ID] INT IDENTITY(1,1) CONSTRAINT [PK_Stocks_ID] PRIMARY KEY,----------------------------------------?
	[ProductID] INT NOT NULL CONSTRAINT [FK_Stocks_ProductID] FOREIGN KEY REFERENCES  [Products]([ID])   ON UPDATE CASCADE ON DELETE NO ACTION,
	[BusinessUnitID] SMALLINT NOT NULL CONSTRAINT [FK_Stocks_BusinessUnitID] FOREIGN KEY REFERENCES  [BusinessUnits]([ID])  ON UPDATE CASCADE ON DELETE NO ACTION,
	[Quantity] SMALLINT NOT NULL CONSTRAINT [CK_Stocks_Quantity] CHECK ([Quantity] > -1),

	CONSTRAINT [UN_Stocks_ProductID_BUID] UNIQUE ([BusinessUnitID], [ProductID])
)
GO


CREATE TABLE [Consigments]
(
	[ID] INT IDENTITY(1,1) CONSTRAINT [PK_Consigments_ID] PRIMARY KEY,
	[EmployeeID] INT NOT NULL CONSTRAINT [FK_Consigments_EmployeeID] FOREIGN KEY REFERENCES [Employees]([ID])  ON UPDATE CASCADE ON DELETE NO ACTION,
	[BusinessUnitID] SMALLINT NOT NULL CONSTRAINT [FK_Consigments_BusinessUnitID] FOREIGN KEY REFERENCES [BusinessUnits]([ID]) ON UPDATE CASCADE ON DELETE NO ACTION,
	[VendorID] SMALLINT NOT NULL CONSTRAINT [FK_Consigments_VendorID] FOREIGN KEY REFERENCES [Vendors]([ID]) ON UPDATE CASCADE ON DELETE NO ACTION,
	[OrderDate]	DATE NOT NULL CONSTRAINT [DEF_Consigments_OrderDate] DEFAULT TRY_CONVERT(DATE, CURRENT_TIMESTAMP),
	[RecievedDate] DATE NULL
)
GO


CREATE TABLE [ConsigmentDetails]
(
	[ConsigmentID] INT NOT NULL CONSTRAINT [FK_ConsigmentDetails_ConsigmentID] FOREIGN KEY REFERENCES [Consigments]([ID]) ON UPDATE CASCADE ON DELETE NO ACTION,
	[ProductID] INT NOT NULL CONSTRAINT [FK_ConsigmentDetails_ProductID] FOREIGN KEY REFERENCES  [Products]([ID])  ON UPDATE  NO ACTION ON DELETE NO ACTION,
	[Quantity] SMALLINT NOT NULL CONSTRAINT [CK_ConsigmentDetails_Quantity] CHECK ([Quantity] > 0),
	[PurchasePrice] NUMERIC (10,2) NOT NULL CONSTRAINT [CK_ConsigmentDetails_PurchasePrice] CHECK ([PurchasePrice] > 0),
	CONSTRAINT [PK_ConsigmentDetails_CID_PID] PRIMARY KEY ([ConsigmentID], [ProductID])
)
GO


CREATE TABLE [Shipments]
(
	[ID] INT IDENTITY(1,1) CONSTRAINT [PK_Shipments] PRIMARY KEY,
	[SourceID] SMALLINT NOT NULL CONSTRAINT [FK_Shipments_BUSourceID] FOREIGN KEY REFERENCES [BusinessUnits]([ID]) ON UPDATE CASCADE ON DELETE CASCADE ,
	[DestinationID] SMALLINT NOT NULL CONSTRAINT [FK_Shipments_BUDestinationID] FOREIGN KEY REFERENCES [BusinessUnits]([ID]) ON UPDATE NO ACTION ON DELETE NO ACTION,
	[EmployeeID] INT NOT NULL CONSTRAINT [FK_Shipments_EmployeeID] FOREIGN KEY REFERENCES [Employees]([ID])ON UPDATE CASCADE ON DELETE CASCADE, 
	[OrderDate] DATETIME NOT NULL CONSTRAINT [DEF_Shipments_OrderDate] DEFAULT TRY_CONVERT(DATETIME, CURRENT_TIMESTAMP),
	[RecievedDate] DATETIME NULL
)
GO


CREATE TABLE [ShipmentDetails]
(
	[ShipmentID] INT CONSTRAINT [FK_ShipmentDetails_ShipmentsID] FOREIGN KEY REFERENCES [Shipments]([ID]) ON UPDATE CASCADE ON DELETE CASCADE,
	[ProductID] INT CONSTRAINT [FK_ShipmentDetails_ProductsID] FOREIGN KEY REFERENCES [Products]([ID])ON UPDATE CASCADE ON DELETE CASCADE,
	[Quantity] SMALLINT NOT NULL CONSTRAINT [CK_ShipmentDetails_Quantity] CHECK ([Quantity] > 0),
	CONSTRAINT [PK_ShipmentDetails_SID_PID] PRIMARY KEY ([ShipmentID], [ProductID])
)
GO


CREATE TABLE [PayType]
(
	[ID] TINYINT IDENTITY(1, 1) CONSTRAINT [PK_PayType_ID] PRIMARY KEY,
	[Title] VARCHAR(25) CONSTRAINT [UN_PayType_Title] UNIQUE
)
GO


CREATE TABLE [Orders]
(
	[ID] INT IDENTITY(1, 1) CONSTRAINT [PK_Orders_ID] PRIMARY KEY,
	[CustomerID] INT NOT NULL CONSTRAINT [FK_Orders_CustomerID] FOREIGN KEY REFERENCES [Customers]([ID]) ON UPDATE CASCADE ON DELETE NO ACTION,
	[BusinessUnitID] SMALLINT NOT NULL CONSTRAINT [FK_Orders_BusinessUnitID] FOREIGN KEY REFERENCES [BusinessUnits]([ID]) ON UPDATE CASCADE ON DELETE NO ACTION,
	[EmployeeID] INT NOT NULL CONSTRAINT [FK_Orders_EmployeeID] FOREIGN KEY REFERENCES [Employees]([ID]) ON UPDATE CASCADE ON DELETE NO ACTION,
	[OperationTime] DATETIME NOT NULL CONSTRAINT [DEF_Orders_OperationTime] DEFAULT TRY_CONVERT(DATETIME, CURRENT_TIMESTAMP),
	[PayTypeID] TINYINT NOT NULL CONSTRAINT [FK_Orders_PayTypeID] FOREIGN KEY REFERENCES [PayType]([ID]) ON UPDATE CASCADE ON DELETE NO ACTION,
	[DiscountID] TINYINT NOT NULL CONSTRAINT [FK_Orders_DiscountID] FOREIGN KEY REFERENCES [Discounts]([ID]) ON UPDATE NO ACTION ON DELETE NO ACTION
)
GO


CREATE TABLE [OrderDetails]
(
	[OrderID] INT NOT NULL CONSTRAINT [FK_OrderDetails_OrderID] FOREIGN KEY REFERENCES [Orders]([ID]) ON UPDATE CASCADE ON DELETE NO ACTION,
	[ProductID] INT NOT NULL CONSTRAINT [FK_OrderDetails_ProductID] FOREIGN KEY REFERENCES [Products]([ID]) ON UPDATE CASCADE ON DELETE NO ACTION,
	[Quantity] SMALLINT NOT NULL CONSTRAINT [CK_OrderDetails_Quantity] CHECK ([Quantity] > 0),
	[UnitPrice] NUMERIC(10, 2) NOT NULL CONSTRAINT [CK_OrderDetails_UnitPrice] CHECK ([UnitPrice] > 0),
	CONSTRAINT [PK_OrderDetails_OID_PID] PRIMARY KEY ([OrderID], [ProductID])
)
GO


CREATE TABLE [ReturnProductTypes]
(
	[ID] TINYINT IDENTITY(1, 1) CONSTRAINT [PK_ReturnProductTypes_ID] PRIMARY KEY,
	[Description] VARCHAR(50) NOT NULL CONSTRAINT [UN_ReturnProductTypes_Description] UNIQUE
)
GO


CREATE TABLE [ReturnProducts]
(
	[ID] INT IDENTITY(1,1) CONSTRAINT [PK_ReturnProducts_ID] PRIMARY KEY,
	[OrderID] INT NOT NULL CONSTRAINT [FK_ReturnProducts_OrderID] FOREIGN KEY REFERENCES [Orders](ID),
	[ProductID] INT NOT NULL CONSTRAINT [FK_ReturnProducts_ProductID] FOREIGN KEY REFERENCES [Products]([ID]),
	[Quantity] SMALLINT NOT NULL CONSTRAINT [CK_ReturnProducts_Quantity] CHECK ([Quantity] > 0),
	[UnitPrice] NUMERIC(10, 2) NOT NULL CONSTRAINT [CK_ReturnProducts_UnitPrice] CHECK ([UnitPrice] > 0),
	[ReturnType] TINYINT NOT NULL CONSTRAINT [FK_ReturnProducts_ReturnType] FOREIGN KEY REFERENCES [ReturnProductTypes]([ID]), 
	[ReturnDate]  DATETIME NOT NULL CONSTRAINT [DEF_ReturnProducts_ReturnDate] DEFAULT TRY_CONVERT(DATETIME, CURRENT_TIMESTAMP),
	[Description] VARCHAR(100) NULL
)
GO


CREATE TABLE [LossTypes]
(
	[ID] TINYINT IDENTITY(1,1) CONSTRAINT [PK_LossTypes_ID] PRIMARY KEY,
	[Description] VARCHAR(50) NOT NULL CONSTRAINT [UN_LossTypes_Description] UNIQUE
)
GO


CREATE TABLE [Losses]
(
	[ID] INT IDENTITY(1,1) CONSTRAINT [PK_Losses_ID] PRIMARY KEY,
	[ProductID] INT NOT NULL CONSTRAINT [FK_Losses_ProductID] FOREIGN KEY REFERENCES [Products]([ID]) ON UPDATE CASCADE ON DELETE NO ACTION,
	[Quantity] SMALLINT NOT NULL CONSTRAINT [CK_Losses_Quantity] CHECK ([Quantity] > 0),
	[Price] NUMERIC(10, 2) NOT NULL CONSTRAINT [CK_Losses_Price] CHECK ([Price] > 0),
	[LossTypeID] TINYINT NOT NULL CONSTRAINT [FK_Losses_LossTypeID] FOREIGN KEY REFERENCES [LossTypes]([ID]) ON UPDATE CASCADE ON DELETE NO ACTION, 
	[LossDate]  DATETIME NOT NULL CONSTRAINT [DEF_Losses_LossDate] DEFAULT TRY_CONVERT(DATETIME, CURRENT_TIMESTAMP),
	[BusinessUnitID] SMALLINT NOT NULL CONSTRAINT [FK_Losses_BusinessUnitID] FOREIGN KEY REFERENCES [BusinessUnits]([ID]) ON UPDATE CASCADE ON DELETE NO ACTION,	
	[Description] VARCHAR(100)	
)
GO


CREATE TABLE [LogActivities]
(
	[ID] INT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_LogActivities_ID] PRIMARY KEY,
	[User] VARCHAR(255) NOT NULL CONSTRAINT [DEF_LogActivities_User] DEFAULT TRY_CONVERT(VARCHAR(255), SYSTEM_USER),
	[Process] VARCHAR(255) NOT NULL,
	[InsertedRows] INT NULL,
	[UpdatedRows] INT NULL,
	[DeletedRows] INT NULL,
	[DateStart] DATETIME NOT NULL CONSTRAINT [DEF_LogActivities_DateStart] DEFAULT TRY_CONVERT(DATETIME, CURRENT_TIMESTAMP),
	[DateEnd] DATETIME NULL,
	[Status] VARCHAR(10) NOT NULL CONSTRAINT [DEF_LogActivities_Status] DEFAULT('STARTED'),
	[ErrorMessage] VARCHAR(255) NULL
)
GO


CREATE TABLE [Regions]
(
	[ID] INT IDENTITY(1,1) NOT NULL,
	[State] VARCHAR(30) NOT NULL,
	[Region] VARCHAR(10) NOT NULL,
)
GO


-------------------------------------line 177 pk?